# Profile to run tests from the new grid. This gets used by the CI.

:test_platform:
  :platform: "grid"
  :grid_options:
    :ip: "172.21.60.35"
    :port: "4444"

:misc:
  :full_screenshots: true
  :restart_on_failure: false
