LIVE = [{ type: "session", payload_action: "start",
          next_seq: [{ type: "playback", payload_action: "playbackRequest" }] },
        { type: "playback", payload_action: "playbackRequest",
          next_seq: [{ type: "playback", payload_action: "streamInitiate" }] },
        { type: "playback", payload_action: "streamInitiate",
          next_seq: [{ type: "playback", payload_action: "start" },
                     { type: "chapter", payload_action: "start" },
                     { type: "chapter", payload_action: "complete" }] },
        { type: "playback", payload_action: "start",
          next_seq: [{ type: "chapter", payload_action: "start" },
                     { type: "chapter", payload_action: "complete" }] },
        { type: "chapter", payload_action: "start",
          next_seq: [{ type: "playback", payload_action: "progress" },
                     { type: "adBreak", payload_action: "complete" }] },
        { type: "playback", payload_action: "progress",
          next_seq: [{ type: "chapter", payload_action: "complete" },
                     { type: "playback", payload_action: "progress" },
                     { type: "playback", payload_action: "stop" },
                     { type: "playback", payload_action: "pauseStop" }] },
        { type: "chapter", payload_action: "complete",
          next_seq: [{ type: "adBreak", payload_action: "start" }] },
        { type: "adBreak", payload_action: "start",
          next_seq: [{ type: "ad", payload_action: "start" }] },
        { type: "ad", payload_action: "start",
          next_seq: [{ type: "ad", payload_action: "progress" },
                     { type: "ad", payload_action: "complete" }] },
        { type: "ad", payload_action: "progress",
          next_seq: [{ type: "ad", payload_action: "progress" },
                     { type: "ad", payload_action: "complete" },
                     { type: "ad", payload_action: "stop" },
                     { type: "ad", payload_action: "pauseStop" }] },
        { type: "ad", payload_action: "complete",
          next_seq: [{ type: "ad", payload_action: "start" },
                     { type: "adBreak", payload_action: "complete" }] },
        { type: "adBreak", payload_action: "complete",
          next_seq: [{ type: "playback", payload_action: "resume" }] },
        { type: "playback", payload_action: "resume",
          next_seq: [{ type: "chapter", payload_action: "start" },
                     { type: "playback", payload_actionL: "progress" }] },
        { type: "playback", payload_action: "stop",
          next_seq: [{ type: "session", payload_action: "stop" }] }].freeze

VERIFYCOUNT_LIVE = [%i[session_start session_stop], %i[ad_break_start ad_break_complete], %i[ad_start ad_complete],
                    %i[ad_start sum_of_num_ads], %i[playback_start playback_stream_initiate], %i[playback_resume ad_break_complete],
                    %i[playback_seekStart playback_seekStop], %i[ad_pauseStart ad_pauseStop], %i[ad_pauseStart ad_resume],
                    %i[ad_buffer_start ad_buffer_stop],
                    %i[playback_buffer_start playback_buffer_stop]].freeze
